"""Fictional editorial fixtures. No venue, availability, price, or allergy claim is live."""

from .models import Experience

CATALOG = [
    Experience(
        id="fire",
        title="على مهل… وعلى الحطب",
        venue="مائدة الحطب",
        neighborhood="حي حطين",
        category="طبق ولحظة",
        cuisine="سعودي",
        image="fire",
        price=145,
        minutes=90,
        editorial=96,
        description="رائحة الحطب أول الترحيب. أطباق سعودية بروح جديدة، ومائدة تكبر بالسوالف. لحظة تستاهل تجمعكم حولها.",
        why="تجربة مشاركة تعطي اللمة مساحة، ونكهة محلية تستحق وقتها.",
        vegetarian_option="قرنبيط مشوي على الحطب مع أرز الأعشاب بدل اللحم.",
        allergens=["حليب", "قمح"],
    ),
    Experience(
        id="sushi",
        title="رحلة صغيرة إلى اليابان",
        venue="طاولة نوري",
        neighborhood="حي الملقا",
        category="مطابخ جديدة",
        cuisine="ياباني",
        image="sushi",
        price=180,
        minutes=75,
        editorial=91,
        description="اجلسوا قريبًا من الشيف. قطع صغيرة، تفاصيل كثيرة، وقائمة تذوّق تأخذكم من نكهة إلى حكاية.",
        why="مطبخ مختلف يوسّع التجربة خارج اختياراتكم المعتادة.",
        vegetarian_option="قائمة ماكي بالخضار والفطر.",
        allergens=["سمك", "قشريات", "صويا", "سمسم", "قمح"],
    ),
    Experience(
        id="levant",
        title="باب صغير، سفرة كبيرة",
        venue="دار الزيتون",
        neighborhood="حي الروضة",
        category="كنوز مخفية",
        cuisine="شامي",
        image="levant",
        price=85,
        minutes=60,
        editorial=90,
        description="في شارع هادئ، خبز يطلع من الفرن ومزّات تتشاركها الأيادي. من الأماكن اللي ودّك تحتفظ بسرّها.",
        why="كنز هادئ، ميزانية مريحة، وخيارات نباتية من أصل المطبخ.",
        vegetarian=True,
        allergens=["سمسم", "قمح", "حليب"],
    ),
    Experience(
        id="pasta",
        title="الباستا تُصنع قدّامك",
        venue="مختبر العجين",
        neighborhood="حي العليا",
        category="افتتاحات",
        cuisine="إيطالي",
        image="pasta",
        price=120,
        minutes=70,
        editorial=87,
        description="عجين طازج، مطبخ مفتوح، وصلصة بسيطة تعطي المكوّن حقّه. بداية جديدة لسه ما يعرفها الكل.",
        why="تجربة افتتاح تجمع عرض التحضير مع طبق مألوف ومحبوب.",
        vegetarian=True,
        allergens=["قمح", "بيض", "حليب"],
    ),
    Experience(
        id="breakfast",
        title="صباح بطعم أوّل",
        venue="فناء الصباح",
        neighborhood="حي الدرعية",
        category="كنوز مخفية",
        cuisine="سعودي",
        image="breakfast",
        price=65,
        minutes=60,
        editorial=85,
        description="تميس دافئ، شكشوكة، وقهوة على طرف الفناء. فطور ما يستعجل الصباح ولا سوالفكم.",
        why="بداية محلية خفيفة على الميزانية قبل يوم طويل.",
        vegetarian=True,
        allergens=["قمح", "بيض", "حليب"],
    ),
    Experience(
        id="bao",
        title="لقمة من آخر العالم",
        venue="بيت الباو",
        neighborhood="حي السليمانية",
        category="مطابخ جديدة",
        cuisine="آسيوي",
        image="bao",
        price=95,
        minutes=45,
        editorial=83,
        description="خبز باو طري وحشوات مليانة نكهة. اطلبوا أكثر من صنف وخلّوا كل لقمة مفاجأة.",
        why="مغامرة صغيرة بالنكهة، تناسب خانة وجبة قصيرة.",
        vegetarian_option="باو الفطر بدل الدجاج.",
        spicy=True,
        mild_option="الصلصة الحارة على الجانب.",
        allergens=["قمح", "صويا", "سمسم"],
    ),
    Experience(
        id="pizza",
        title="حواف تستاهل الانتظار",
        venue="فرن الحارة",
        neighborhood="حي النرجس",
        category="افتتاحات",
        cuisine="إيطالي",
        image="pizza",
        price=80,
        minutes=55,
        editorial=81,
        description="فرن صغير وعجينة تأخذ وقتها. بيتزا نابولية إلى وسط الطاولة، عشان كل أحد يذوق.",
        why="اختيار مشاركة مرن يقرّب الأذواق المختلفة.",
        vegetarian=True,
        allergens=["قمح", "حليب"],
    ),
    Experience(
        id="coffee",
        title="قهوة… وباقي الحكاية",
        venue="ظل البن",
        neighborhood="حي الياسمين",
        category="طبق ولحظة",
        cuisine="قهوة وحلى",
        image="coffee",
        price=45,
        minutes=40,
        editorial=78,
        description="قهوة مقطّرة وحلى تمر دافئ في ركن هادئ. خلوها موعدًا كاملًا، مو محطة مستعجلة.",
        why="وقفة هادئة للنهاية؛ مرنة إذا احتاجت وجبة ثانية مكانها.",
        vegetarian=True,
        allergens=["حليب", "قمح", "مكسرات"],
    ),
    Experience(
        id="dessert",
        title="ختامها فستق",
        venue="قطعة سكر",
        neighborhood="حي العقيق",
        category="طبق ولحظة",
        cuisine="قهوة وحلى",
        image="dessert",
        price=50,
        minutes=40,
        editorial=75,
        description="طبقات خفيفة وفستق محمّص. ختام حلو تتقاسمونه، وتطوّلون عنده السالفة.",
        why="لحظة حلوة إضافية نحفظها إذا ما وسعها الوقت.",
        vegetarian=True,
        allergens=["مكسرات", "قمح", "حليب", "بيض"],
    ),
]

CATALOG_IDS = {item.id for item in CATALOG}
