/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": unknown;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Experience"][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateGroup"];
          "text/json": components["schemas"]["CreateGroup"];
          "application/*+json": components["schemas"]["CreateGroup"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GroupCreated"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          group_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GroupView"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          group_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Settings"];
          "text/json": components["schemas"]["Settings"];
          "application/*+json": components["schemas"]["Settings"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GroupView"];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          group_id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Preferences"];
          "text/json": components["schemas"]["Preferences"];
          "application/*+json": components["schemas"]["Preferences"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GroupView"];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/members/{member_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          group_id: string;
          member_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["GroupView"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/invites/{code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          code: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["InviteView"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/invites/{code}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          code: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Preferences"];
          "text/json": components["schemas"]["Preferences"];
          "application/*+json": components["schemas"]["Preferences"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["MemberCreated"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/invites/{code}/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          code: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Member"];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          code: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Preferences"];
          "text/json": components["schemas"]["Preferences"];
          "application/*+json": components["schemas"]["Preferences"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Member"];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {unknown} */
    Allergen:
      | "مكسرات"
      | "فول سوداني"
      | "حليب"
      | "قمح"
      | "سمسم"
      | "قشريات"
      | "سمك"
      | "بيض"
      | "صويا";
    /** @enum {unknown} */
    Category: "مطابخ جديدة" | "كنوز مخفية" | "افتتاحات" | "طبق ولحظة";
    CreateGroup: {
      /** @default لَمّتنا في الرياض */
      title: string;
      preferences: components["schemas"]["Preferences"];
    };
    /** @enum {unknown} */
    Cuisine: "سعودي" | "ياباني" | "إيطالي" | "شامي" | "آسيوي" | "قهوة وحلى";
    Decision: {
      experience_id: string;
      priority: components["schemas"]["Priority"];
      reason: string;
      adaptations: string[];
      /** Format: double */
      score: number;
    };
    Experience: {
      id: string;
      title: string;
      venue: string;
      neighborhood: string;
      category: components["schemas"]["Category"];
      cuisine: components["schemas"]["Cuisine"];
      description: string;
      why: string;
      image: string;
      /** Format: int32 */
      price: number;
      /** Format: int32 */
      minutes: number;
      /** Format: int32 */
      editorial: number;
      vegetarian?: boolean;
      vegetarian_option?: null | string;
      spicy?: boolean;
      mild_option?: null | string;
      allergens?: components["schemas"]["Allergen"][];
      verified_free_of?: components["schemas"]["Allergen"][];
    };
    GroupCreated: {
      organizer_token: string;
      group: components["schemas"]["GroupView"];
    };
    GroupView: {
      id: string;
      title: string;
      invite_code: string;
      settings: components["schemas"]["Settings"];
      members: components["schemas"]["Member"][];
      plan: components["schemas"]["Plan"];
    };
    InviteView: {
      title: string;
      member_names: string[];
      /** Format: int32 */
      slots: number;
      selected: components["schemas"]["Decision"][];
      anchor_issue: null | string;
      /** Format: int32 */
      consumed: number;
    };
    Member: {
      id: string;
      preferences: components["schemas"]["Preferences"];
      /** @default false */
      organizer: boolean;
    };
    MemberCreated: {
      member_token: string;
      member: components["schemas"]["Member"];
    };
    Plan: {
      selected: components["schemas"]["Decision"][];
      pocket: components["schemas"]["PocketItem"][];
      anchor_issue: null | string;
      /** Format: int32 */
      consumed: number;
      /** Format: int32 */
      available: number;
      /** Format: int32 */
      unfilled: number;
    };
    PocketItem: {
      experience_id: string;
      reason: string;
      /** @default false */
      blocked: boolean;
    };
    Preferences: {
      name: string;
      /** @default مقيم */
      role: components["schemas"]["Role"];
      cuisines?: components["schemas"]["Cuisine"][];
      allergies?: components["schemas"]["Allergen"][];
      vegetarian?: boolean;
      mild?: boolean;
      /**
       * Format: int32
       * @default 200
       */
      budget: number;
    };
    /** @enum {unknown} */
    Priority: "ركيزة" | "أساسية" | "مرنة";
    /** @enum {unknown} */
    Role: "مقيم" | "زائر";
    Settings: {
      /**
       * Format: int32
       * @default 9
       */
      slots: number;
      /** @default fire */
      anchor_id: null | string;
      pocket_ids?: string[];
      completed_ids?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
