/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiences */
    get: operations["experiences_api_experiences_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Group */
    post: operations["create_group_api_groups_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Group */
    get: operations["get_group_api_groups__group_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Settings */
    put: operations["update_settings_api_groups__group_id__settings_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Organizer */
    put: operations["update_organizer_api_groups__group_id__profile_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/members/{member_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Member */
    delete: operations["remove_member_api_groups__group_id__members__member_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/invites/{code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Invite */
    get: operations["invite_api_invites__code__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/invites/{code}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Join Group */
    post: operations["join_group_api_invites__code__members_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/invites/{code}/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get My Preferences */
    get: operations["get_my_preferences_api_invites__code__me_get"];
    /** Update My Preferences */
    put: operations["update_my_preferences_api_invites__code__me_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CreateGroup */
    CreateGroup: {
      /**
       * Title
       * @default لَمّتنا في الرياض
       */
      title: string;
      preferences: components["schemas"]["Preferences"];
    };
    /** Decision */
    Decision: {
      /** Experience Id */
      experience_id: string;
      /**
       * Priority
       * @enum {string}
       */
      priority: "ركيزة" | "أساسية" | "مرنة";
      /** Reason */
      reason: string;
      /** Adaptations */
      adaptations?: string[];
      /** Score */
      score: number;
    };
    /** ErrorResponse */
    ErrorResponse: {
      /** Detail */
      detail: string;
    };
    /** Experience */
    Experience: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Venue */
      venue: string;
      /** Neighborhood */
      neighborhood: string;
      /**
       * Category
       * @enum {string}
       */
      category: "مطابخ جديدة" | "كنوز مخفية" | "افتتاحات" | "طبق ولحظة";
      /**
       * Cuisine
       * @enum {string}
       */
      cuisine: "سعودي" | "ياباني" | "إيطالي" | "شامي" | "آسيوي" | "قهوة وحلى";
      /** Description */
      description: string;
      /** Why */
      why: string;
      /** Image */
      image: string;
      /** Price */
      price: number;
      /** Minutes */
      minutes: number;
      /** Editorial */
      editorial: number;
      /**
       * Vegetarian
       * @default false
       */
      vegetarian: boolean;
      /** Vegetarian Option */
      vegetarian_option?: string | null;
      /**
       * Spicy
       * @default false
       */
      spicy: boolean;
      /** Mild Option */
      mild_option?: string | null;
      /** Allergens */
      allergens?: (
        | "مكسرات"
        | "فول سوداني"
        | "حليب"
        | "قمح"
        | "سمسم"
        | "قشريات"
        | "سمك"
        | "بيض"
        | "صويا"
      )[];
      /** Verified Free Of */
      verified_free_of?: (
        | "مكسرات"
        | "فول سوداني"
        | "حليب"
        | "قمح"
        | "سمسم"
        | "قشريات"
        | "سمك"
        | "بيض"
        | "صويا"
      )[];
    };
    /** GroupCreated */
    GroupCreated: {
      /** Organizer Token */
      organizer_token: string;
      group: components["schemas"]["GroupView"];
    };
    /** GroupView */
    GroupView: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Invite Code */
      invite_code: string;
      settings: components["schemas"]["Settings"];
      /** Members */
      members: components["schemas"]["Member"][];
      plan: components["schemas"]["Plan"];
    };
    /** InviteView */
    InviteView: {
      /** Title */
      title: string;
      /** Member Names */
      member_names: string[];
      /** Slots */
      slots: number;
      /** Selected */
      selected: components["schemas"]["Decision"][];
      /** Anchor Issue */
      anchor_issue?: string | null;
      /** Consumed */
      consumed: number;
    };
    /** Member */
    Member: {
      /** Id */
      id: string;
      preferences: components["schemas"]["Preferences"];
      /**
       * Organizer
       * @default false
       */
      organizer: boolean;
    };
    /** MemberCreated */
    MemberCreated: {
      /** Member Token */
      member_token: string;
      member: components["schemas"]["Member"];
    };
    /** Plan */
    Plan: {
      /** Selected */
      selected: components["schemas"]["Decision"][];
      /** Pocket */
      pocket: components["schemas"]["PocketItem"][];
      /** Anchor Issue */
      anchor_issue?: string | null;
      /** Consumed */
      consumed: number;
      /** Available */
      available: number;
      /** Unfilled */
      unfilled: number;
    };
    /** PocketItem */
    PocketItem: {
      /** Experience Id */
      experience_id: string;
      /** Reason */
      reason: string;
      /**
       * Blocked
       * @default false
       */
      blocked: boolean;
    };
    /** Preferences */
    Preferences: {
      /** Name */
      name: string;
      /**
       * Role
       * @default مقيم
       * @enum {string}
       */
      role: "مقيم" | "زائر";
      /** Cuisines */
      cuisines?: (
        "سعودي" | "ياباني" | "إيطالي" | "شامي" | "آسيوي" | "قهوة وحلى"
      )[];
      /** Allergies */
      allergies?: (
        | "مكسرات"
        | "فول سوداني"
        | "حليب"
        | "قمح"
        | "سمسم"
        | "قشريات"
        | "سمك"
        | "بيض"
        | "صويا"
      )[];
      /**
       * Vegetarian
       * @default false
       */
      vegetarian: boolean;
      /**
       * Mild
       * @default false
       */
      mild: boolean;
      /**
       * Budget
       * @default 200
       */
      budget: number;
    };
    /** Settings */
    Settings: {
      /**
       * Slots
       * @default 9
       */
      slots: number;
      /**
       * Anchor Id
       * @default fire
       */
      anchor_id: string | null;
      /** Pocket Ids */
      pocket_ids?: string[];
      /** Completed Ids */
      completed_ids?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  experiences_api_experiences_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Experience"][];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_group_api_groups_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGroup"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupCreated"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_group_api_groups__group_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        group_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_settings_api_groups__group_id__settings_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        group_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Settings"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_organizer_api_groups__group_id__profile_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        group_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Preferences"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove_member_api_groups__group_id__members__member_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        group_id: string;
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  invite_api_invites__code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InviteView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  join_group_api_invites__code__members_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Preferences"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberCreated"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_my_preferences_api_invites__code__me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Member"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_my_preferences_api_invites__code__me_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Preferences"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Member"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
