/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v2/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations["register_api_v2_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v2_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_api_v2_auth_me_get"];
    /** Update Profile */
    put: operations["update_profile_api_v2_auth_me_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_api_v2_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/experiences/{experience_id}/google-rating": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Google Rating */
    get: operations["google_rating_api_v2_experiences__experience_id__google_rating_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/experiences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiences */
    get: operations["experiences_api_v2_experiences_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/experiences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Experiences */
    get: operations["experiences_api_experiences_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Groups */
    get: operations["groups_api_v2_groups_get"];
    put?: never;
    /** Create Circle */
    post: operations["create_circle_api_v2_groups_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/legacy/claim": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Claim Legacy */
    post: operations["claim_legacy_api_v2_legacy_claim_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups/{circle_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Group */
    get: operations["group_api_v2_groups__circle_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups/{circle_id}/title": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Rename */
    put: operations["rename_api_v2_groups__circle_id__title_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups/{circle_id}/me/preferences": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Preferences */
    put: operations["preferences_api_v2_groups__circle_id__me_preferences_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups/{circle_id}/me/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Options */
    patch: operations["options_api_v2_groups__circle_id__me_options_patch"];
    trace?: never;
  };
  "/api/v2/invites/{code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Invite */
    get: operations["invite_api_v2_invites__code__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/invites/{code}/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Join */
    post: operations["join_api_v2_invites__code__join_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups/{circle_id}/members/{member_id}/remove": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Remove */
    post: operations["remove_api_v2_groups__circle_id__members__member_id__remove_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups/{circle_id}/members/{member_id}/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore */
    post: operations["restore_api_v2_groups__circle_id__members__member_id__restore_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups/{circle_id}/transfer": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transfer */
    post: operations["transfer_api_v2_groups__circle_id__transfer_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups/{circle_id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archive */
    post: operations["archive_api_v2_groups__circle_id__archive_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups/{circle_id}/outings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create */
    post: operations["create_api_v2_groups__circle_id__outings_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/outings/{outing_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get */
    get: operations["get_api_v2_outings__outing_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/outings/{outing_id}/me/attendance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Attendance */
    put: operations["attendance_api_v2_outings__outing_id__me_attendance_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/outings/{outing_id}/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Settings */
    put: operations["settings_api_v2_outings__outing_id__settings_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/outings/{outing_id}/coordinator": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Coordinator */
    put: operations["coordinator_api_v2_outings__outing_id__coordinator_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/outings/{outing_id}/close": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Close */
    post: operations["close_api_v2_outings__outing_id__close_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/outings/{outing_id}/fun/{member_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send Fun */
    post: operations["send_fun_api_v2_outings__outing_id__fun__member_id__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/outings/{outing_id}/fun/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Dismiss Fun */
    delete: operations["dismiss_fun_api_v2_outings__outing_id__fun_me_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/outings/{outing_id}/rounds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create */
    post: operations["create_api_v2_outings__outing_id__rounds_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/rounds/{round_id}/my-vote": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Vote */
    put: operations["vote_api_v2_rounds__round_id__my_vote_put"];
    post?: never;
    /** Withdraw */
    delete: operations["withdraw_api_v2_rounds__round_id__my_vote_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/rounds/{round_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel */
    post: operations["cancel_api_v2_rounds__round_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/rounds/{round_id}/resolve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resolve */
    post: operations["resolve_api_v2_rounds__round_id__resolve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/rounds/{round_id}/draw": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Draw */
    post: operations["draw_api_v2_rounds__round_id__draw_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/groups/{circle_id}/me/skin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Circle Skin */
    put: operations["circle_skin_api_v2_groups__circle_id__me_skin_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v2/outings/{outing_id}/me/skin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Outing Skin */
    put: operations["outing_skin_api_v2_outings__outing_id__me_skin_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Account Plans */
    get: operations["account_plans_api_groups_get"];
    put?: never;
    /** Create Group */
    post: operations["create_group_api_groups_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/account": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Save To Account */
    put: operations["save_to_account_api_groups__group_id__account_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/title": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Rename Plan */
    put: operations["rename_plan_api_groups__group_id__title_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Group */
    get: operations["get_group_api_groups__group_id__get"];
    put?: never;
    post?: never;
    /** Delete Plan */
    delete: operations["delete_plan_api_groups__group_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Settings */
    put: operations["update_settings_api_groups__group_id__settings_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/profile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Organizer */
    put: operations["update_organizer_api_groups__group_id__profile_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/groups/{group_id}/members/{member_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Member */
    delete: operations["remove_member_api_groups__group_id__members__member_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/invites/{code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Invite */
    get: operations["invite_api_invites__code__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/invites/{code}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Join Group */
    post: operations["join_group_api_invites__code__members_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/invites/{code}/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get My Preferences */
    get: operations["get_my_preferences_api_invites__code__me_get"];
    /** Update My Preferences */
    put: operations["update_my_preferences_api_invites__code__me_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/quick-decisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Quick Decision */
    post: operations["quick_decision_api_quick_decisions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/plan-invitations/{kind}/{source_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Editor */
    get: operations["get_editor_api_plan_invitations__kind___source_id__get"];
    /** Save */
    put: operations["save_api_plan_invitations__kind___source_id__put"];
    post?: never;
    /** Revoke */
    delete: operations["revoke_api_plan_invitations__kind___source_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/shared-plans/{code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public Invitation */
    get: operations["public_invitation_api_shared_plans__code__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Account */
    Account: {
      /** Id */
      id: string;
      /** Handle */
      handle: string;
      /** Name */
      name: string;
    };
    /** AccountProfile */
    AccountProfile: {
      /** Name */
      name: string;
    };
    /** AccountSession */
    AccountSession: {
      /** Token */
      token: string;
      account: components["schemas"]["Account"];
    };
    /** Acknowledged */
    Acknowledged: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /** AttendanceChange */
    AttendanceChange: {
      /**
       * Attendance
       * @enum {string}
       */
      attendance: "pending" | "going" | "declined";
      /** Budget Override */
      budget_override?: number | null;
    };
    /** CircleCreate */
    CircleCreate: {
      /** Title */
      title: string;
      preferences: components["schemas"]["Preferences"];
    };
    /** CircleJoin */
    CircleJoin: {
      preferences: components["schemas"]["Preferences"];
      /** Legacy Token */
      legacy_token?: string | null;
    };
    /** CircleMember */
    CircleMember: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Is Owner */
      is_owner: boolean;
      /** Is Me */
      is_me: boolean;
      /** Claimed */
      claimed: boolean;
      /**
       * Status
       * @enum {string}
       */
      status: "active" | "removed";
      /** Fun Opt In */
      fun_opt_in: boolean;
      skin?: components["schemas"]["Skin"] | null;
      preferences?: components["schemas"]["Preferences"] | null;
    };
    /** CircleSummary */
    CircleSummary: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Member Count */
      member_count: number;
      /** Pinned */
      pinned: boolean;
      /** Is Owner */
      is_owner: boolean;
      /** Archived */
      archived: boolean;
    };
    /** CircleView */
    CircleView: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Invite Code */
      invite_code: string;
      /** Is Owner */
      is_owner: boolean;
      /** Archived */
      archived: boolean;
      me: components["schemas"]["CircleMember"];
      /** Pinned */
      pinned: boolean;
      /** Members */
      members: components["schemas"]["CircleMember"][];
      /** Outings */
      outings: components["schemas"]["OutingSummary"][];
    };
    /** CreateGroup */
    CreateGroup: {
      /**
       * Title
       * @default لَمّتنا في الرياض
       */
      title: string;
      preferences: components["schemas"]["Preferences"];
      settings?: components["schemas"]["Settings"];
    };
    /** Credentials */
    Credentials: {
      /** Handle */
      handle: string;
      /**
       * Password
       * Format: password
       */
      password: string;
    };
    /** Decision */
    Decision: {
      /** Experience Id */
      experience_id: string;
      /**
       * Priority
       * @enum {string}
       */
      priority: "ركيزة" | "أساسية" | "مرنة";
      /** Reason */
      reason: string;
      /** Adaptations */
      adaptations?: string[];
      /** Score */
      score: number;
    };
    /** ErrorResponse */
    ErrorResponse: {
      /** Detail */
      detail: string;
    };
    /** Experience */
    Experience: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Venue */
      venue: string;
      /** Neighborhood */
      neighborhood: string;
      /**
       * Category
       * @enum {string}
       */
      category: "مطابخ جديدة" | "كنوز مخفية" | "افتتاحات" | "طبق ولحظة";
      /**
       * Cuisine
       * @enum {string}
       */
      cuisine: "سعودي" | "ياباني" | "إيطالي" | "شامي" | "آسيوي" | "قهوة وحلى";
      /** Description */
      description: string;
      /** Why */
      why: string;
      /** Image */
      image: string;
      /** Price */
      price: number;
      /** Minutes */
      minutes: number;
      /** Editorial */
      editorial: number;
      /**
       * Vegetarian
       * @default false
       */
      vegetarian: boolean;
      /** Vegetarian Option */
      vegetarian_option?: string | null;
      /**
       * Spicy
       * @default false
       */
      spicy: boolean;
      /** Mild Option */
      mild_option?: string | null;
      /** Allergens */
      allergens?: (
        | "مكسرات"
        | "فول سوداني"
        | "حليب"
        | "قمح"
        | "سمسم"
        | "قشريات"
        | "سمك"
        | "بيض"
        | "صويا"
      )[];
      /** Verified Free Of */
      verified_free_of?: (
        | "مكسرات"
        | "فول سوداني"
        | "حليب"
        | "قمح"
        | "سمسم"
        | "قشريات"
        | "سمك"
        | "بيض"
        | "صويا"
      )[];
      /** Outing Traits */
      outing_traits?: ("quiet" | "sharing" | "discovery")[];
      /** Suggested Dishes */
      suggested_dishes?: string[];
      /** Google Place Id */
      google_place_id?: string | null;
      /**
       * Is Demo
       * @default true
       */
      is_demo: boolean;
    };
    /** FunCard */
    FunCard: {
      /** Target Id */
      target_id: string;
      /** Target Name */
      target_name: string;
      /** Remaining Seconds */
      remaining_seconds: number;
    };
    /** GoogleRating */
    GoogleRating: {
      /**
       * Status
       * @enum {string}
       */
      status: "available" | "demo" | "unlinked" | "unavailable";
      /** Rating */
      rating?: number | null;
      /** Review Count */
      review_count?: number | null;
      /** Checked At */
      checked_at?: string | null;
      /** Attributions */
      attributions?: components["schemas"]["RatingAttribution"][];
    };
    /** GroupCreated */
    GroupCreated: {
      /** Organizer Token */
      organizer_token: string | null;
      group: components["schemas"]["GroupView"];
    };
    /** GroupView */
    GroupView: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Owner Account Id */
      owner_account_id?: string | null;
      /** Invite Code */
      invite_code: string;
      settings: components["schemas"]["Settings"];
      /** Members */
      members: components["schemas"]["Member"][];
      plan: components["schemas"]["Plan"];
    };
    /** InvitationChange */
    InvitationChange: {
      details: components["schemas"]["InvitationDetails"];
      /** Expected Revision */
      expected_revision: number | null;
    };
    /** InvitationDetails */
    InvitationDetails: {
      /** Title */
      title: string;
      /**
       * Message
       * @default لكم مكان على الطاولة.
       */
      message: string;
      /**
       * When Label
       * @default
       */
      when_label: string;
      /**
       * Meeting Note
       * @default
       */
      meeting_note: string;
      /**
       * Theme
       * @default palm
       * @enum {string}
       */
      theme: "palm" | "saffron" | "rose";
    };
    /** InvitationEditor */
    InvitationEditor: {
      details: components["schemas"]["InvitationDetails"];
      plan: components["schemas"]["SharedPlan"];
      /** Code */
      code: string | null;
      /** Revision */
      revision: number | null;
    };
    /** InvitationRevoke */
    InvitationRevoke: {
      /** Expected Revision */
      expected_revision: number;
    };
    /** InviteView */
    InviteView: {
      context?: components["schemas"]["OutingContext"];
      /** Title */
      title: string;
      /** Member Names */
      member_names: string[];
      /** Slots */
      slots: number;
      /** Selected */
      selected: components["schemas"]["Decision"][];
      /** Anchor Issue */
      anchor_issue?: string | null;
      /** Consumed */
      consumed: number;
    };
    /** LegacyClaim */
    LegacyClaim: {
      /** Group Id */
      group_id: string;
      /**
       * Owner Token
       * Format: password
       */
      owner_token: string;
    };
    /** Member */
    Member: {
      /** Id */
      id: string;
      preferences: components["schemas"]["Preferences"];
      /**
       * Organizer
       * @default false
       */
      organizer: boolean;
    };
    /** MemberCreated */
    MemberCreated: {
      /** Member Token */
      member_token: string;
      member: components["schemas"]["Member"];
    };
    /** MemberSelection */
    MemberSelection: {
      /** Member Id */
      member_id: string;
    };
    /** MembershipOptions */
    MembershipOptions: {
      /** Pinned */
      pinned?: boolean | null;
      /** Fun Opt In */
      fun_opt_in?: boolean | null;
    };
    /** OutingContext */
    OutingContext: {
      /**
       * Kind
       * @default any
       * @enum {string}
       */
      kind: "any" | "family" | "friends";
      /** Priorities */
      priorities?: ("quiet" | "sharing" | "discovery")[];
    };
    /** OutingCreate */
    OutingCreate: {
      /** Title */
      title: string;
      /**
       * Slots
       * @default 3
       */
      slots: number;
      /** Coordinator Id */
      coordinator_id?: string | null;
      context?: components["schemas"]["OutingContext"];
    };
    /** OutingSummary */
    OutingSummary: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /**
       * Status
       * @enum {string}
       */
      status: "open" | "closed";
      /** Going */
      going: number;
      /** Slots */
      slots: number;
      /** Coordinator Name */
      coordinator_name: string;
    };
    /** OutingView */
    OutingView: {
      /** Id */
      id: string;
      /** Circle Id */
      circle_id: string;
      /** Title */
      title: string;
      /** Owner Name */
      owner_name: string;
      /** Coordinator Name */
      coordinator_name: string;
      /** Coordinator Id */
      coordinator_id: string;
      /**
       * Status
       * @enum {string}
       */
      status: "open" | "closed";
      settings: components["schemas"]["Settings"];
      plan: components["schemas"]["Plan"];
      /** Participants */
      participants: components["schemas"]["Participant"][];
      /** My Member Id */
      my_member_id: string;
      /** Can Manage */
      can_manage: boolean;
      /** Is Owner */
      is_owner: boolean;
      /** Eligible Ids */
      eligible_ids: string[];
      round: components["schemas"]["RoundView"] | null;
      /** Cards */
      cards: components["schemas"]["FunCard"][];
      /** Planning Revision */
      planning_revision: number;
    };
    /** Participant */
    Participant: {
      /** Member Id */
      member_id: string;
      /** Name */
      name: string;
      /**
       * Attendance
       * @enum {string}
       */
      attendance: "pending" | "going" | "declined";
      /** Is Me */
      is_me: boolean;
      /** Is Coordinator */
      is_coordinator: boolean;
      /** Is Owner */
      is_owner: boolean;
      /** Fun Opt In */
      fun_opt_in: boolean;
      /** Claimed */
      claimed: boolean;
      /** Fun Used */
      fun_used: boolean;
      skin?: components["schemas"]["Skin"] | null;
      skin_override?: components["schemas"]["Skin"] | null;
      preferences?: components["schemas"]["Preferences"] | null;
      /** Budget Override */
      budget_override?: number | null;
    };
    /** Plan */
    Plan: {
      /** Selected */
      selected: components["schemas"]["Decision"][];
      /** Pocket */
      pocket: components["schemas"]["PocketItem"][];
      /** Anchor Issue */
      anchor_issue?: string | null;
      /** Consumed */
      consumed: number;
      /** Available */
      available: number;
      /** Unfilled */
      unfilled: number;
    };
    /** PlanSettingsChange */
    PlanSettingsChange: {
      /**
       * Slots
       * @default 9
       */
      slots: number;
      /**
       * Anchor Id
       * @default fire
       */
      anchor_id: string | null;
      /** Pocket Ids */
      pocket_ids?: string[];
      /** Completed Ids */
      completed_ids?: string[];
      context?: components["schemas"]["OutingContext"];
      expected?: components["schemas"]["Settings"] | null;
    };
    /** PlanSummary */
    PlanSummary: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Slots */
      slots: number;
      /** Consumed */
      consumed: number;
    };
    /** PocketItem */
    PocketItem: {
      /** Experience Id */
      experience_id: string;
      /** Reason */
      reason: string;
      /**
       * Blocked
       * @default false
       */
      blocked: boolean;
    };
    /** Preferences */
    Preferences: {
      /** Name */
      name: string;
      /**
       * Role
       * @default مقيم
       * @enum {string}
       */
      role: "مقيم" | "زائر";
      /** Cuisines */
      cuisines?: (
        "سعودي" | "ياباني" | "إيطالي" | "شامي" | "آسيوي" | "قهوة وحلى"
      )[];
      /** Allergies */
      allergies?: (
        | "مكسرات"
        | "فول سوداني"
        | "حليب"
        | "قمح"
        | "سمسم"
        | "قشريات"
        | "سمك"
        | "بيض"
        | "صويا"
      )[];
      /**
       * Vegetarian
       * @default false
       */
      vegetarian: boolean;
      /**
       * Mild
       * @default false
       */
      mild: boolean;
      /**
       * Budget
       * @default 200
       */
      budget: number;
    };
    /** PublicCircle */
    PublicCircle: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Member Count */
      member_count: number;
    };
    /** PublicInvitation */
    PublicInvitation: {
      details: components["schemas"]["InvitationDetails"];
      plan: components["schemas"]["SharedPlan"];
      /** Read At */
      read_at: string;
      /** Created At */
      created_at: string;
    };
    /** QuickRequest */
    QuickRequest: {
      /** Members */
      members: components["schemas"]["Preferences"][];
      /** Minutes */
      minutes: number;
      /** Neighborhood */
      neighborhood?: string | null;
      context?: components["schemas"]["OutingContext"];
      /** Excluded Ids */
      excluded_ids?: string[];
    };
    /** QuickResult */
    QuickResult: {
      /** Choices */
      choices: components["schemas"]["Decision"][];
      /** Message */
      message: string;
      /**
       * Duration Note
       * @default مدة التجربة تقديرية؛ لا تشمل الطريق أو الانتظار. تأكد من وقت الفتح وتوفر التجربة قبل الذهاب.
       */
      duration_note: string;
    };
    /** RatingAttribution */
    RatingAttribution: {
      /** Provider */
      provider: string;
      /** Provider Uri */
      provider_uri: string;
    };
    /** Registration */
    Registration: {
      /** Handle */
      handle: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /** Name */
      name: string;
    };
    /** RoundCreate */
    RoundCreate: {
      /**
       * Mode
       * @enum {string}
       */
      mode: "vote" | "draw";
      /** Experience Ids */
      experience_ids: string[];
    };
    /** RoundOption */
    RoundOption: {
      /** Experience Id */
      experience_id: string;
      /** Votes */
      votes: number;
    };
    /** RoundView */
    RoundView: {
      /** Id */
      id: string;
      /**
       * Mode
       * @enum {string}
       */
      mode: "vote" | "draw";
      /**
       * Status
       * @enum {string}
       */
      status: "open" | "tied" | "resolved" | "invalidated";
      /** Options */
      options: components["schemas"]["RoundOption"][];
      /** My Vote */
      my_vote: string | null;
      /** Voter Count */
      voter_count: number;
      /** Voted Count */
      voted_count: number;
      /** Can Vote */
      can_vote: boolean;
      /** Result Id */
      result_id: string | null;
      /** Resolved By */
      resolved_by: ("vote" | "draw" | "only_option") | null;
      /** Resolved At */
      resolved_at: string | null;
    };
    /** SaveToAccount */
    SaveToAccount: {
      /**
       * Owner Token
       * Format: password
       */
      owner_token: string;
    };
    /** Settings */
    Settings: {
      /**
       * Slots
       * @default 9
       */
      slots: number;
      /**
       * Anchor Id
       * @default fire
       */
      anchor_id: string | null;
      /** Pocket Ids */
      pocket_ids?: string[];
      /** Completed Ids */
      completed_ids?: string[];
      context?: components["schemas"]["OutingContext"];
    };
    /** SettingsChange */
    SettingsChange: {
      settings: components["schemas"]["Settings"];
      expected: components["schemas"]["Settings"];
    };
    /** SharedExperience */
    SharedExperience: {
      /** Id */
      id: string;
      /** Title */
      title: string;
      /** Venue */
      venue: string;
      /** Neighborhood */
      neighborhood: string;
      /** Cuisine */
      cuisine: string;
      /** Image */
      image: string;
      /** Price */
      price: number;
      /** Minutes */
      minutes: number;
      /**
       * Priority
       * @enum {string}
       */
      priority: "ركيزة" | "أساسية" | "مرنة";
      /** Reason */
      reason: string;
      /** Dishes */
      dishes: string[];
      /** Options */
      options: string[];
      /** Is Demo */
      is_demo: boolean;
      /** Maps Url */
      maps_url: string;
      /** Maps Verified */
      maps_verified: boolean;
    };
    /** SharedPlan */
    SharedPlan: {
      context: components["schemas"]["OutingContext"];
      /** Entries */
      entries: components["schemas"]["SharedExperience"][];
      /** Consumed */
      consumed: number;
      /** Available */
      available: number;
      /** Unfilled */
      unfilled: number;
      /** Anchor Unavailable */
      anchor_unavailable: boolean;
      /** Archived */
      archived: boolean;
    };
    /** Skin */
    Skin: {
      /**
       * Version
       * @default 1
       * @constant
       */
      version: 1;
      /**
       * Persona
       * @enum {string}
       */
      persona: "host" | "on_way" | "you_choose";
      /**
       * Tone
       * @default warm
       * @enum {string}
       */
      tone: "light" | "warm" | "deep";
      /**
       * Outfit
       * @default casual
       * @enum {string}
       */
      outfit: "thobe" | "abaya" | "casual";
      /**
       * Color
       * @default palm
       * @enum {string}
       */
      color: "palm" | "saffron" | "rose" | "sky";
      /**
       * Accessory
       * @default none
       * @enum {string}
       */
      accessory: "none" | "glasses";
      /**
       * Expression
       * @default smile
       * @enum {string}
       */
      expression: "smile" | "wink" | "side_eye";
      /**
       * Phrase
       * @default classic
       * @enum {string}
       */
      phrase: "classic" | "extra";
    };
    /** SkinChange */
    SkinChange: {
      skin: components["schemas"]["Skin"] | null;
      expected: components["schemas"]["Skin"] | null;
    };
    /** TitleChange */
    TitleChange: {
      /** Title */
      title: string;
    };
    /** VoteChange */
    VoteChange: {
      /** Experience Id */
      experience_id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  register_api_v2_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Registration"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountSession"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  login_api_v2_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Credentials"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountSession"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  me_api_v2_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_profile_api_v2_auth_me_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountProfile"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  logout_api_v2_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Acknowledged"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  google_rating_api_v2_experiences__experience_id__google_rating_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        experience_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GoogleRating"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  experiences_api_v2_experiences_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Experience"][];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  experiences_api_experiences_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Experience"][];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  groups_api_v2_groups_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleSummary"][];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_circle_api_v2_groups_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CircleCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  claim_legacy_api_v2_legacy_claim_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LegacyClaim"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  group_api_v2_groups__circle_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        circle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  rename_api_v2_groups__circle_id__title_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        circle_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TitleChange"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  preferences_api_v2_groups__circle_id__me_preferences_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        circle_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Preferences"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  options_api_v2_groups__circle_id__me_options_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        circle_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MembershipOptions"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  invite_api_v2_invites__code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicCircle"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  join_api_v2_invites__code__join_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CircleJoin"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove_api_v2_groups__circle_id__members__member_id__remove_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        circle_id: string;
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  restore_api_v2_groups__circle_id__members__member_id__restore_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        circle_id: string;
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  transfer_api_v2_groups__circle_id__transfer_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        circle_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberSelection"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  archive_api_v2_groups__circle_id__archive_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        circle_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_api_v2_groups__circle_id__outings_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        circle_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OutingCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_api_v2_outings__outing_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        outing_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  attendance_api_v2_outings__outing_id__me_attendance_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        outing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttendanceChange"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  settings_api_v2_outings__outing_id__settings_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        outing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsChange"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  coordinator_api_v2_outings__outing_id__coordinator_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        outing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MemberSelection"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  close_api_v2_outings__outing_id__close_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        outing_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  send_fun_api_v2_outings__outing_id__fun__member_id__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        outing_id: string;
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  dismiss_fun_api_v2_outings__outing_id__fun_me_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        outing_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_api_v2_outings__outing_id__rounds_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        outing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RoundCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  vote_api_v2_rounds__round_id__my_vote_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        round_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VoteChange"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  withdraw_api_v2_rounds__round_id__my_vote_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        round_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  cancel_api_v2_rounds__round_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        round_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  resolve_api_v2_rounds__round_id__resolve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        round_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  draw_api_v2_rounds__round_id__draw_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        round_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  circle_skin_api_v2_groups__circle_id__me_skin_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        circle_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SkinChange"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CircleView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  outing_skin_api_v2_outings__outing_id__me_skin_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        outing_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SkinChange"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OutingView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  account_plans_api_groups_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PlanSummary"][];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_group_api_groups_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGroup"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupCreated"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  save_to_account_api_groups__group_id__account_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        group_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SaveToAccount"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  rename_plan_api_groups__group_id__title_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        group_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TitleChange"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_group_api_groups__group_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        group_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_plan_api_groups__group_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        group_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Acknowledged"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_settings_api_groups__group_id__settings_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        group_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlanSettingsChange"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_organizer_api_groups__group_id__profile_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        group_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Preferences"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  remove_member_api_groups__group_id__members__member_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        group_id: string;
        member_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GroupView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  invite_api_invites__code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InviteView"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  join_group_api_invites__code__members_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Preferences"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberCreated"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_my_preferences_api_invites__code__me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Member"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_my_preferences_api_invites__code__me_put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Preferences"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Member"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  quick_decision_api_quick_decisions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuickRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuickResult"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_editor_api_plan_invitations__kind___source_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        kind: "plan" | "outing";
        source_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationEditor"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  save_api_plan_invitations__kind___source_id__put: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        kind: "plan" | "outing";
        source_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvitationChange"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitationEditor"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  revoke_api_plan_invitations__kind___source_id__delete: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        kind: "plan" | "outing";
        source_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InvitationRevoke"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Acknowledged"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  public_invitation_api_shared_plans__code__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PublicInvitation"];
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Invalid request */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
